//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ExcelWorkbookBud {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(3)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class FeuilLogWebService : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox textBoxLogWebService;
        
        internal Microsoft.Office.Tools.Excel.Controls.CheckBox checkBoxLogWebServeur;
        
        internal Microsoft.Office.Tools.Excel.Controls.CheckBox checkBoxLogX3;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox textBoxInputXML;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox textBoxOutputXML;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public FeuilLogWebService(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Feuil5", "Feuil5") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.FeuilLogWebService = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.textBoxLogWebService = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "34329DD4D35E9D348913BC473CEEDB438DFD83", "34329DD4D35E9D348913BC473CEEDB438DFD83", this, "textBoxLogWebService");
            this.checkBoxLogWebServeur = new Microsoft.Office.Tools.Excel.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "4CAE0D6D54EA7644EFB4843D451E30B8464514", "4CAE0D6D54EA7644EFB4843D451E30B8464514", this, "checkBoxLogWebServeur");
            this.checkBoxLogX3 = new Microsoft.Office.Tools.Excel.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "588BE465D5FECD54F235AE4356DF25E2B25CB5", "588BE465D5FECD54F235AE4356DF25E2B25CB5", this, "checkBoxLogX3");
            this.textBoxInputXML = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "62A3E9D396CC14642066808E66A986179421F6", "62A3E9D396CC14642066808E66A986179421F6", this, "textBoxInputXML");
            this.textBoxOutputXML = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "7B38C3FD5772CF74E267B7FA7C2DAF0253B9F7", "7B38C3FD5772CF74E267B7FA7C2DAF0253B9F7", this, "textBoxOutputXML");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // textBoxLogWebService
            // 
            this.textBoxLogWebService.AcceptsReturn = true;
            this.textBoxLogWebService.AcceptsTab = true;
            this.textBoxLogWebService.AllowDrop = true;
            this.textBoxLogWebService.MinimumSize = new System.Drawing.Size(0, 200);
            this.textBoxLogWebService.Multiline = true;
            this.textBoxLogWebService.Name = "textBoxLogWebService";
            this.textBoxLogWebService.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            // 
            // checkBoxLogWebServeur
            // 
            this.checkBoxLogWebServeur.Name = "checkBoxLogWebServeur";
            this.checkBoxLogWebServeur.Text = "Active";
            // 
            // checkBoxLogX3
            // 
            this.checkBoxLogX3.Name = "checkBoxLogX3";
            this.checkBoxLogX3.Text = "Active";
            // 
            // textBoxInputXML
            // 
            this.textBoxInputXML.AcceptsReturn = true;
            this.textBoxInputXML.AcceptsTab = true;
            this.textBoxInputXML.AllowDrop = true;
            this.textBoxInputXML.MinimumSize = new System.Drawing.Size(0, 200);
            this.textBoxInputXML.Multiline = true;
            this.textBoxInputXML.Name = "textBoxInputXML";
            this.textBoxInputXML.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            // 
            // textBoxOutputXML
            // 
            this.textBoxOutputXML.AcceptsReturn = true;
            this.textBoxOutputXML.AcceptsTab = true;
            this.textBoxOutputXML.AllowDrop = true;
            this.textBoxOutputXML.MinimumSize = new System.Drawing.Size(0, 200);
            this.textBoxOutputXML.Multiline = true;
            this.textBoxOutputXML.Name = "textBoxOutputXML";
            this.textBoxOutputXML.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            // 
            // Feuil5
            // 
            this.textBoxLogWebService.BindingContext = this.BindingContext;
            this.checkBoxLogWebServeur.BindingContext = this.BindingContext;
            this.checkBoxLogX3.BindingContext = this.BindingContext;
            this.textBoxInputXML.BindingContext = this.BindingContext;
            this.textBoxOutputXML.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static FeuilLogWebService _FeuilLogWebService;
        
        internal static FeuilLogWebService FeuilLogWebService {
            get {
                return _FeuilLogWebService;
            }
            set {
                if ((_FeuilLogWebService == null)) {
                    _FeuilLogWebService = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
