//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ExcelWorkbookBud {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class FeuilGlobalParams : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.NamedRange POOLWS;
        
        internal Microsoft.Office.Tools.Excel.NamedRange URLWSWSDL;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3TYPWS;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3ENDPOINT;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3WEBSERVER;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3WEBSERVERPORT;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3HTTP;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3L1;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3L2;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3L4;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3L3;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3L5;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3TYPWS2;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3WSENDPOINT;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public FeuilGlobalParams(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Feuil1", "Feuil1") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.FeuilGlobalParams = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.POOLWS.BeginInit();
            this.URLWSWSDL.BeginInit();
            this.X3TYPWS.BeginInit();
            this.X3ENDPOINT.BeginInit();
            this.X3WEBSERVER.BeginInit();
            this.X3WEBSERVERPORT.BeginInit();
            this.X3HTTP.BeginInit();
            this.X3L1.BeginInit();
            this.X3L2.BeginInit();
            this.X3L4.BeginInit();
            this.X3L3.BeginInit();
            this.X3L5.BeginInit();
            this.X3TYPWS2.BeginInit();
            this.X3WSENDPOINT.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.X3WSENDPOINT.EndInit();
            this.X3TYPWS2.EndInit();
            this.X3L5.EndInit();
            this.X3L3.EndInit();
            this.X3L4.EndInit();
            this.X3L2.EndInit();
            this.X3L1.EndInit();
            this.X3HTTP.EndInit();
            this.X3WEBSERVERPORT.EndInit();
            this.X3WEBSERVER.EndInit();
            this.X3ENDPOINT.EndInit();
            this.X3TYPWS.EndInit();
            this.URLWSWSDL.EndInit();
            this.POOLWS.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.POOLWS = Globals.Factory.CreateNamedRange(null, null, "POOLWS", "POOLWS", this);
            this.URLWSWSDL = Globals.Factory.CreateNamedRange(null, null, "URLWSWSDL", "URLWSWSDL", this);
            this.X3TYPWS = Globals.Factory.CreateNamedRange(null, null, "X3TYPWS", "X3TYPWS", this);
            this.X3ENDPOINT = Globals.Factory.CreateNamedRange(null, null, "X3ENDPOINT", "X3ENDPOINT", this);
            this.X3WEBSERVER = Globals.Factory.CreateNamedRange(null, null, "X3WEBSERVER", "X3WEBSERVER", this);
            this.X3WEBSERVERPORT = Globals.Factory.CreateNamedRange(null, null, "X3WEBSERVERPORT", "X3WEBSERVERPORT", this);
            this.X3HTTP = Globals.Factory.CreateNamedRange(null, null, "X3HTTP", "X3HTTP", this);
            this.X3L1 = Globals.Factory.CreateNamedRange(null, null, "X3L1", "X3L1", this);
            this.X3L2 = Globals.Factory.CreateNamedRange(null, null, "X3L2", "X3L2", this);
            this.X3L4 = Globals.Factory.CreateNamedRange(null, null, "X3L4", "X3L4", this);
            this.X3L3 = Globals.Factory.CreateNamedRange(null, null, "X3L3", "X3L3", this);
            this.X3L5 = Globals.Factory.CreateNamedRange(null, null, "X3L5", "X3L5", this);
            this.X3TYPWS2 = Globals.Factory.CreateNamedRange(null, null, "X3TYPWS2", "X3TYPWS2", this);
            this.X3WSENDPOINT = Globals.Factory.CreateNamedRange(null, null, "X3WSENDPOINT", "X3WSENDPOINT", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // POOLWS
            // 
            this.POOLWS.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // URLWSWSDL
            // 
            this.URLWSWSDL.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3TYPWS
            // 
            this.X3TYPWS.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3ENDPOINT
            // 
            this.X3ENDPOINT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3WEBSERVER
            // 
            this.X3WEBSERVER.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3WEBSERVERPORT
            // 
            this.X3WEBSERVERPORT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3HTTP
            // 
            this.X3HTTP.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3L1
            // 
            this.X3L1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3L2
            // 
            this.X3L2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3L4
            // 
            this.X3L4.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3L3
            // 
            this.X3L3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3L5
            // 
            this.X3L5.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3TYPWS2
            // 
            this.X3TYPWS2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3WSENDPOINT
            // 
            this.X3WSENDPOINT.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // FeuilGlobalParams
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.X3WSENDPOINT.Dispose();
            this.X3TYPWS2.Dispose();
            this.X3L5.Dispose();
            this.X3L3.Dispose();
            this.X3L4.Dispose();
            this.X3L2.Dispose();
            this.X3L1.Dispose();
            this.X3HTTP.Dispose();
            this.X3WEBSERVERPORT.Dispose();
            this.X3WEBSERVER.Dispose();
            this.X3ENDPOINT.Dispose();
            this.X3TYPWS.Dispose();
            this.URLWSWSDL.Dispose();
            this.POOLWS.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static FeuilGlobalParams _FeuilGlobalParams;
        
        internal static FeuilGlobalParams FeuilGlobalParams {
            get {
                return _FeuilGlobalParams;
            }
            set {
                if ((_FeuilGlobalParams == null)) {
                    _FeuilGlobalParams = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
