//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ExcelWorkbookBud {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(4)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class FeuilCalculation : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3LOGIN;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3CRIT1;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3CRIT2;
        
        internal Microsoft.Office.Tools.Excel.NamedRange X3CRIT3;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button buttonLoadDatasForm;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button buttonConnection;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button buttonUpdateDatas;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox comboBoxSite;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button buttonLoadDep;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn Column1;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn Column2;
        
        private System.ComponentModel.IContainer components;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public FeuilCalculation(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Feuil9", "Feuil9") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.FeuilCalculation = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.X3LOGIN.BeginInit();
            this.X3CRIT1.BeginInit();
            this.X3CRIT2.BeginInit();
            this.X3CRIT3.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.X3CRIT3.EndInit();
            this.X3CRIT2.EndInit();
            this.X3CRIT1.EndInit();
            this.X3LOGIN.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.X3LOGIN = Globals.Factory.CreateNamedRange(null, null, "X3LOGIN", "X3LOGIN", this);
            this.X3CRIT1 = Globals.Factory.CreateNamedRange(null, null, "X3CRIT1", "X3CRIT1", this);
            this.X3CRIT2 = Globals.Factory.CreateNamedRange(null, null, "X3CRIT2", "X3CRIT2", this);
            this.X3CRIT3 = Globals.Factory.CreateNamedRange(null, null, "X3CRIT3", "X3CRIT3", this);
            this.buttonLoadDatasForm = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1C4C17B64188DA14F361A09B15FA83444BB461", "1C4C17B64188DA14F361A09B15FA83444BB461", this, "buttonLoadDatasForm");
            this.buttonConnection = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "3440F871E36868349C03A8333240F048B63C23", "3440F871E36868349C03A8333240F048B63C23", this, "buttonConnection");
            this.buttonUpdateDatas = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "6C1B41F5B69E906409E6BD14656C2EACB9C9B6", "6C1B41F5B69E906409E6BD14656C2EACB9C9B6", this, "buttonUpdateDatas");
            this.comboBoxSite = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "19A4D649210DF414BCC196221CFB0701CAA1A1", "19A4D649210DF414BCC196221CFB0701CAA1A1", this, "comboBoxSite");
            this.buttonLoadDep = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "2768EAA742288924E9628CB32F6335925F36A2", "2768EAA742288924E9628CB32F6335925F36A2", this, "buttonLoadDep");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            this.Column1 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Column2 = new System.Windows.Forms.DataGridViewTextBoxColumn();
            // 
            // buttonLoadDatasForm
            // 
            this.buttonLoadDatasForm.Name = "buttonLoadDatasForm";
            this.buttonLoadDatasForm.Text = "Load forecast";
            // 
            // buttonConnection
            // 
            this.buttonConnection.Name = "buttonConnection";
            this.buttonConnection.Text = "Connection";
            // 
            // buttonUpdateDatas
            // 
            this.buttonUpdateDatas.Name = "buttonUpdateDatas";
            this.buttonUpdateDatas.Text = "Update forecast";
            // 
            // comboBoxSite
            // 
            this.comboBoxSite.BackColor = System.Drawing.SystemColors.Window;
            this.comboBoxSite.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxSite.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.comboBoxSite.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.comboBoxSite.ItemHeight = 15;
            this.comboBoxSite.Margin = new System.Windows.Forms.Padding(0);
            this.comboBoxSite.Name = "comboBoxSite";
            this.comboBoxSite.Tag = "";
            // 
            // buttonLoadDep
            // 
            this.buttonLoadDep.Name = "buttonLoadDep";
            this.buttonLoadDep.Text = "Load Site & Products sales";
            // 
            // X3LOGIN
            // 
            this.X3LOGIN.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3CRIT1
            // 
            this.X3CRIT1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3CRIT2
            // 
            this.X3CRIT2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // X3CRIT3
            // 
            this.X3CRIT3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Column1
            // 
            this.Column1.HeaderText = "Column1";
            this.Column1.Name = "Column1";
            // 
            // Column2
            // 
            this.Column2.HeaderText = "Column2";
            this.Column2.Name = "Column2";
            // 
            // FeuilCalculation
            // 
            this.buttonLoadDatasForm.BindingContext = this.BindingContext;
            this.buttonConnection.BindingContext = this.BindingContext;
            this.buttonUpdateDatas.BindingContext = this.BindingContext;
            this.comboBoxSite.BindingContext = this.BindingContext;
            this.buttonLoadDep.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.X3CRIT3.Dispose();
            this.X3CRIT2.Dispose();
            this.X3CRIT1.Dispose();
            this.X3LOGIN.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static FeuilCalculation _FeuilCalculation;
        
        internal static FeuilCalculation FeuilCalculation {
            get {
                return _FeuilCalculation;
            }
            set {
                if ((_FeuilCalculation == null)) {
                    _FeuilCalculation = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
